[WIP] [cvnirc-core] Try to recognize again JOIN message
Broken: Does not compile.

* Introduce cvnirc::core::IRCProto::KeyMessageArg.
* Change holder to use the correct types for keyType and keyListType,
  now. (Resolves 2 FIXMEs.)
* Implement conversion in IRCProtoClient::_loadMsgArgTypes().
* Try to register JOIN message in IRCProtoClient::_loadMsgTypeVocabIn();
  this does not work, compile time error:
  "no matching function for call to [...]" (unintelligible)
* Try to handle JOIN message again
  in IRCCoreContext::receiveIRCProtoMessage().